[project]
name = "pyperformance_bm_numpy"
requires-python = ">=3.9"
dependencies = [
    "pyperf",
    "numpy==1.25.0",
]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "numpy"
